dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - travis_retry pip install -q poetry
  - travis_retry poetry install
script:
  - poetry run mypy -p ecode
  - travis_retry poetry run pytest -v --cov=ecode
  - travis_retry bash <(curl -s https://codecov.io/bash)


