dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - travis_retry pip install -r requirements-dev.txt
script:
  - mypy -p ecode
  - travis_retry pytest
  - travis_retry bash <(curl -s https://codecov.io/bash)


